kiegroup/lienzo-core

pom.xml
adding producing sources jar as good standard for Nexus validation rule
=> adding producing sources jar as good standard

src/main/java/com/ait/lienzo/client/core/shape/AbstractDirectionalMultiPointShape.java, src/main/java/com/ait/lienzo/client/core/shape/IDirectionalMultiPointShape.java, src/main/java/com/ait/lienzo/client/core/shape/PolyLine.java, src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnection.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnector.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresConnectorControl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/ShapeControlUtils.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresControlPointHandlerImpl.java, src/main/java/com/ait/lienzo/client/core/util/Geometry.java
Stunner - Add support for polylines
- Connectors now support polylines.
- Polyline segments now snap at straight angles.
JIRA:
https://issues.jboss.org/browse/JBPM-6672
@romartin 
@tiagodolphine 
@LuboTerifaj
=> JBPM-6672 - Stunner - Add support for polylines

src/main/java/com/ait/lienzo/client/core/shape/AbstractMultiPathPartShape.java
Hey @hasys 
This is the cherry-pick for https://github.com/kiegroup/lienzo-core/pull/13 into `7.7.x`
Thanks!
=> [7.7.x] RHBA-684: Do not throw exception on size constraints validation.

src/main/java/com/ait/lienzo/client/core/shape/wires/WiresMagnet.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresDockingControl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java
Cherry pick the commit dfc63f7bfbe4aaba927ecc4e58a6c403097427fa 
@romartin 
@LuboTerifaj
=>  RHPAM-754 Docking issues (cherry-pick JBPM-6178 to 7.7.x)

src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeShapeHandler.java
See https://issues.jboss.org/browse/RHPAM-838
---
Cherry picked from https://github.com/kiegroup/lienzo-core/pull/19
---
- https://github.com/kiegroup/lienzo-core/pull/23
- https://github.com/kiegroup/lienzo-tests/pull/19
- https://github.com/kiegroup/kie-wb-common/pull/1702
=> [7.7.x] RHPAM-838 (JBPM-7118): Stunner - Mediators (zoom,pan) not working properly

src/main/java/com/ait/lienzo/client/core/image/ImageLoader.java, src/main/java/com/ait/lienzo/client/core/image/ImageProxy.java, src/main/java/com/ait/lienzo/client/core/shape/wires/DefaultSelectionListener.java, src/main/java/com/ait/lienzo/client/core/shape/wires/MagnetManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresContainer.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresLayoutContainer.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresShape.java, src/main/java/com/ait/lienzo/client/widget/LienzoHandlerManager.java, src/main/java/com/ait/lienzo/client/widget/LienzoPanel.java
Hey @hasys @manstis 
Here are some bug fixings for some of the memory leaks on the lienzo side. 
Related PRs:
- https://github.com/kiegroup/lienzo-tests/pull/18
- https://github.com/kiegroup/kie-wb-common/pull/1685
Thanks!
=> JBPM-5462: Fixing some memory leaks

src/main/java/com/ait/lienzo/client/core/image/ImageLoader.java, src/main/java/com/ait/lienzo/client/core/image/ImageProxy.java, src/main/java/com/ait/lienzo/client/core/shape/wires/DefaultSelectionListener.java, src/main/java/com/ait/lienzo/client/core/shape/wires/MagnetManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresContainer.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresLayoutContainer.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresShape.java, src/main/java/com/ait/lienzo/client/widget/LienzoHandlerManager.java, src/main/java/com/ait/lienzo/client/widget/LienzoPanel.java
Hey @hasys 
This is the cherry-pick for https://github.com/kiegroup/lienzo-core/pull/21 into `7.7.x`
**Related to**:
* https://github.com/kiegroup/lienzo-tests/pull/21
* https://github.com/kiegroup/kie-wb-common/pull/1749
Thanks!
=> [7.7.x] RHPAM-427: Fixing some memory leaks - most relevant ones in LienzoPanel and Pictures

src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/INativeContext2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/image/ImageProxy.java, src/main/java/com/ait/lienzo/client/core/shape/Node.java
JBPM-7145 cherry pick dbf246fb132dfcff047bdac777579b884ce8d337 + fix to NPE on IE
@romartin
=> [7.7.x] RHPAM-878 Stunner - SVG persisted on backend when saving a diagram 

src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnector.java
Hey @hasys 
This is the cherry-pick for https://github.com/kiegroup/lienzo-core/pull/32
**Includes** https://github.com/kiegroup/lienzo-tests/pull/24
Thanks!
=> JBPM-7272 & JBPM-7269: Fixed errors once removing some nodes

src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/INativeContext2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/shape/Shape.java
Cherry pick commit ca20013d40d1ca84b6e8a577a15d910fd3c23cd8 to 7.7.x
@romartin
=> [7.7.x] RHPAM-1003 Stunner - Diagram SVG is not highlighted on the WB

src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/config/LienzoCore.java
Disabling the HiDPI, I just need to know how to test this. Running locally it is ok, but I was not able to see improvements here on linux with chrome/firefox.
@romartin 
@mdproctor
=> JBPM-7305 - Disable/Enable HiDPI on Stunner / Lienzo

src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java
See:
- https://github.com/ahome-it/lienzo-core/pull/218
- https://issues.jboss.org/browse/JBPM-7118
---
No feature is being added by this PR, and no behavior is being broken. I'm just syncing the PR with the blessed repository.
Do not merge before getting the https://github.com/ahome-it/lienzo-core/pull/218 merged.
---
- https://github.com/kiegroup/lienzo-core/pull/26
- https://github.com/kiegroup/lienzo-tests/pull/20
=> JBPM-7118: Stunner - Mediators (zoom,pan) not working properly (2)

src/main/java/com/ait/lienzo/client/widget/LienzoHandlerManager.java
This PR slightly decreases the codebase by reusing method that checks pressed mouse button.
@romartin would you mind to have a look?
Ensemble:
- #43 
- kiegroup/lienzo-tests#27
=> Introduce private method for checking pressed mouse button

src/main/java/com/ait/lienzo/client/core/animation/LayerRedrawManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImpl.java, src/main/java/com/ait/lienzo/client/widget/LienzoHandlerManager.java
Cherry pick c8236ab38c989f12e21e1a22c84701c73d8f7d91 related to https://issues.jboss.org/browse/JBPM-7332
@romartin
@LuboTerifaj
=> [7.7.x ] RHPAM-1158 Performance improvements: Lienzo Layer batch() to avoid requestAnimation	

src/main/java/com/ait/lienzo/client/core/config/LienzoCorePlugin.java, src/main/java/com/ait/lienzo/client/core/image/Image.java, src/main/java/com/ait/lienzo/client/core/image/ImageElementProxy.java, src/main/java/com/ait/lienzo/client/core/image/ImageLoadCallback.java, src/main/java/com/ait/lienzo/client/core/image/ImageStrip.java, src/main/java/com/ait/lienzo/client/core/image/ImageStrips.java, src/main/java/com/ait/lienzo/client/core/shape/GroupOf.java, src/main/java/com/ait/lienzo/client/core/shape/IDestroyable.java, src/main/java/com/ait/lienzo/client/core/shape/Picture.java, src/main/java/com/ait/lienzo/shared/core/types/ShapeType.java
Hey @hasys 
This is an important performance improvement for the next 7.0.2... please can you give it some priority?
See https://issues.jboss.org/browse/RHPAM-1281
Follows up on:
* https://github.com/kiegroup/lienzo-tests/pull/31
* https://github.com/kiegroup/kie-wb-common/pull/1920
Thanks!
=> [7.7.x] RHPAM-1281: Support for image strips

src/main/java/com/ait/lienzo/client/core/config/LienzoCore.java
@romartin New PR with correct branch name. Tests in PR https://github.com/kiegroup/lienzo-tests/pull/33
=> Setter from HiDPI mode was not working

src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresShape.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresParentPickerControl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AbstractWiresParentPickerControl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresControlPointHandlerImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresParentPickerControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/picker/ColorMapBackedPicker.java
Hey @hasys 
See https://issues.jboss.org/browse/JBPM-7022
Related to
https://github.com/kiegroup/lienzo-tests/pull/36
https://github.com/kiegroup/kie-wb-common/pull/1982
Thanks!
=> JBPM-7022: Stunner - not possible to move Selected nodes in some conditions

src/main/java/com/ait/lienzo/client/core/shape/AbstractDirectionalMultiPointShape.java, src/main/java/com/ait/lienzo/client/core/shape/PolyLine.java, src/main/java/com/ait/lienzo/client/core/shape/wires/DefaultSelectionListener.java, src/main/java/com/ait/lienzo/client/core/shape/wires/IControlPointsAcceptor.java, src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnector.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresShape.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresConnectorControl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresControlPointHandler.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresHandlerFactory.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresParentPickerControl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/ShapeControlUtils.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeShapeHandler.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectionControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorHandlerImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresControlPointHandlerImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresHandlerFactoryImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresParentPickerControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeHandlerImpl.java
Hey @hasys @tiagodolphine 
This is the continuation of https://github.com/kiegroup/lienzo-core/pull/55 but targeting now `master` branch.
I've squashed all work from the PR referenced above and rebased with master, so it includes all improvements and fixes you previously found as well.
Thanks!
=> JBPM-7450: Wires connectors - bendpoints fixes and improvements

src/main/java/com/ait/lienzo/client/core/shape/BezierCurve.java, src/main/java/com/ait/lienzo/client/core/types/BoundingBox.java, src/main/java/com/ait/lienzo/client/core/types/BoundingPoints.java, src/main/java/com/ait/lienzo/client/core/types/PathPartList.java, src/main/java/com/ait/lienzo/client/core/types/Point2DArray.java, src/main/java/com/ait/lienzo/client/core/util/Geometry.java
Hey @hasys 
This is the new version for this https://github.com/kiegroup/lienzo-core/pull/35, which includes the tests. Tests are here https://github.com/kiegroup/lienzo-tests/pull/25
Thanks!
=> JBPM-7267: Improve BB computation performance

src/main/java/com/ait/lienzo/client/core/shape/AbstractMultiPointShape.java, src/main/java/com/ait/lienzo/client/core/shape/Line.java, src/main/java/com/ait/lienzo/client/core/shape/OrthogonalPolyLine.java, src/main/java/com/ait/lienzo/client/core/shape/PolyLine.java, src/main/java/com/ait/lienzo/client/core/shape/Polygon.java, src/main/java/com/ait/lienzo/client/core/shape/Spline.java, src/main/java/com/ait/lienzo/client/core/shape/TextBoundsWrap.java, src/main/java/com/ait/lienzo/client/core/shape/Triangle.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnection.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnector.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresContainer.java, src/main/java/com/ait/lienzo/client/core/shape/wires/event/WiresConnectorPointsChangedEvent.java, src/main/java/com/ait/lienzo/client/core/shape/wires/event/WiresConnectorPointsChangedHandler.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresControlPointHandlerImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabel.java, src/main/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabelFactory.java, src/main/java/com/ait/lienzo/client/core/util/Geometry.java
Hey @hasys @tiagodolphine 
See https://issues.jboss.org/browse/JBPM-5566
Related to
https://github.com/kiegroup/lienzo-tests/pull/41
https://github.com/kiegroup/kie-wb-common/pull/2078
Thanks!!
=> JBPM-5566: [Wires] Labels on connectors

src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AlignAndDistributeControlImpl.java
https://issues.jboss.org/browse/JBPM-7668
There was an issue with a flag that signals if the control's attribute
changes should be handled. It was causing problems when using undo/redo
and probably other actions as well.
=> JBPM-7668 (Stunner) - Align and distribute doesn't work properly

src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorHandlerImpl.java
Hi @romartin,
this is a workaround as we discussed. Test can be found here: https://github.com/kiegroup/lienzo-tests/pull/51
=> JBPM-7854 - Error while moving the mouse over the explorer panel

pom.xml
Companion PR to https://github.com/kiegroup/lienzo-tests/pull/54
=> Align surefire version with kiegroup projects

src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java
Hey @hasys 
These are the cherry-picks for https://github.com/kiegroup/kie-wb-common/pull/2345 into `7.14.x` branch.
Please this is a blocker for this week - can you give priority to it? See https://issues.jboss.org/browse/RHPAM-1809
Assembly:
https://github.com/kiegroup/lienzo-tests/pull/58
https://github.com/kiegroup/kie-wb-common/pull/2383
Thanks!!!
=> [7.14.x] RHPAM-1809: Fixed some issues related to docking.

src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java
Hey @hasys @tiagodolphine 
See https://github.com/kiegroup/kie-wb-common/pull/2345/
Tests here - https://github.com/kiegroup/lienzo-tests/pull/56
Thanks!
=> JBPM-8044: [Stunner] Docking is not working when the preview panel is opened.

src/main/java/com/ait/lienzo/client/core/shape/AbstractPathClipper.java, src/main/java/com/ait/lienzo/client/core/shape/Movie.java, src/main/java/com/ait/lienzo/client/core/shape/OrthogonalPolyLine.java, src/main/java/com/ait/lienzo/client/core/shape/TextUtils.java, src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnector.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresLayoutContainer.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresShapeControlHandleList.java
Hi @tiagodolphine, @LuboTerifaj there are some fixed issued repored by sonar: [see here](https://sonarcloud.io/project/issues?id=org.kie%3Alienzo-core&resolved=false&types=BUG) for more details.
Contains:
* Fixed possible null pointers
* typo fixes
* formatting fixes
* removed unused list
* equal if statements merged to one
* implemented hashCode function for class with overriden equals method
* Cast operand of the division operation to a double if double expected
CC @romartin 
Assembly:
https://github.com/kiegroup/lienzo-core/pull/89
https://github.com/kiegroup/lienzo-tests/pull/67
=> Fixing issues reported by findbug plugin

src/main/java/com/ait/lienzo/client/core/config/LienzoCore.java, src/main/java/com/ait/lienzo/client/core/mediator/MouseBoxZoomMediator.java, src/main/java/com/ait/lienzo/client/core/mediator/MousePanMediator.java, src/main/java/com/ait/lienzo/client/core/shape/Node.java, src/main/java/com/ait/lienzo/client/widget/panel/LienzoBoundsPanel.java, src/main/java/com/ait/lienzo/client/widget/panel/LienzoPanel.java, src/main/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelHandlerManager.java, src/main/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelImpl.java, src/main/java/com/ait/lienzo/client/widget/panel/impl/PreviewLayer.java, src/main/java/com/ait/lienzo/client/widget/panel/mediators/AbstractPanelMediator.java, src/main/java/com/ait/lienzo/client/widget/panel/mediators/PanelMediators.java, src/main/java/com/ait/lienzo/client/widget/panel/mediators/PanelPreviewMediator.java, src/main/java/com/ait/lienzo/client/widget/panel/mediators/RestrictedMousePanMediator.java, src/main/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanel.java, src/main/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelHandler.java, src/main/java/com/ait/lienzo/client/widget/panel/util/PanelTransformUtils.java
Hey @hasys @jomarko 
See https://issues.jboss.org/browse/JBPM-7443
See https://issues.jboss.org/browse/JBPM-7429
See also the feature's description at https://github.com/kiegroup/kie-wb-common/pull/2534
Assembly with 
https://github.com/kiegroup/kie-wb-common/pull/2534
https://github.com/kiegroup/lienzo-tests/pull/72
Thanks!
=> JBPM-7443 & JBPM-7429: Stunner - Zooming and panning improvements

src/main/java/com/ait/lienzo/client/core/shape/TextBoundsWrap.java, src/main/java/com/ait/lienzo/client/core/shape/TextLineBreakTruncateWrapper.java, src/main/java/com/ait/lienzo/client/core/shape/TextTruncateWrapper.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresShape.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/AbstractContainerLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/IContainerLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/direction/DirectionContainerLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/direction/DirectionLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/direction/DirectionLayoutBuilder.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/direction/HorizontalLayoutFactory.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/direction/VerticalLayoutFactory.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/label/LabelContainerLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/label/LabelLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/size/IMaxSizeLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/size/SizeConstraints.java, src/main/java/com/ait/lienzo/client/core/shape/wires/layout/size/SizeConstraintsContainerLayout.java, src/main/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabel.java
- Wrapping text
- Multi-line support
- New node label layout
Assembly:
https://github.com/kiegroup/lienzo-tests/pull/73
It should be considered the related PR:
https://github.com/kiegroup/kie-wb-common/pull/2557
@romartin 
@LuboTerifaj
=> JBPM-6454 Stunner - rethink text wrapping and fonts for nodes

src/main/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanel.java
* https://github.com/kiegroup/lienzo-core/pull/95
* https://github.com/kiegroup/lienzo-tests/pull/75
=> AF-1936: Unexpected error when deleting project with Business Process

src/main/java/com/ait/lienzo/client/core/mediator/MouseBoxZoomMediator.java, src/main/java/com/ait/lienzo/client/widget/panel/mediators/PanelPreviewMediator.java
Hey @tiagobento 
Here is the fix for the preview area mediator, see [JBPM-8386](https://issues.redhat.com/browse/JBPM-8386)
Assembly with https://github.com/kiegroup/lienzo-tests/pull/83
Thannks!
=> JBPM-8386: Stunner - Preview mediator does nothing for small selection areas.

src/main/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelHandler.java
@romartin, @inodeman: Could you review this PR please?
Assembly with https://github.com/kiegroup/lienzo-tests/pull/92
=> KOGITO-1196: Editor goes back horizontally when diagram is bigger than default

src/main/java/com/ait/lienzo/client/core/shape/toolbox/ToolboxVisibilityExecutors.java, src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlUtils.java, src/main/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelHandler.java
@romartin, @inodeman : Please, could you review this PR?
See https://issues.redhat.com/browse/JBPM-9175
Assembly with:
* https://github.com/kiegroup/kie-wb-common/pull/3319
* https://github.com/kiegroup/lienzo-core/pull/111
* https://github.com/kiegroup/lienzo-tests/pull/94
=> JBPM-9175: Stunner - Usability improvements around selection / drag capabilities

pom.xml
**Thank you for submitting this pull request**
**JIRA**: _(please edit the JIRA link if it exists)_ 
[link](https://www.example.com)
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* paste the link(s) from GitHub here
* link 2
* link 3 etc.
<pre>
How to retest a PR or trigger a specific build:
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>
=> Mbiarnes test

pom.xml
**Upgrade JDK 11 + GWT 2.9**
Feel free to comment and/or raise any concerns.
This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039
Thanks guys for that!
**JIRA**:
[AF-1799](https://issues.redhat.com/browse/AF-1799)
**Referenced Pull Requests**:
- https://github.com/errai/errai/pull/408 [**merged**]
- https://github.com/kiegroup/lienzo-core/pull/134 [**approved**]
- https://github.com/kiegroup/lienzo-tests/pull/109 [**approved**]
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1488 [**approved**]
- https://github.com/kiegroup/kie-soup/pull/161 [**approved**]
- https://github.com/kiegroup/appformer/pull/1059 [**approved**]
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/469 [**approved**] …
=> AF-1799: Upgrade JDK 11 + GWT 2.9

src/main/java/com/ait/lienzo/shared/core/types/Color.java, src/test/java/com/ait/lienzo/shared/core/tests/ColorTest.java
Hey @romartin; 
This is an important fix cherry-picked from  https://github.com/dikalo/lienzo-core/pull/225/files.
Could you review this PR Please?
Thanks
=> Color.toBrowserRGBA alpha fix
