kiegroup/lienzo-core

src/main/java/com/ait/lienzo/client/widget/LienzoHandlerManager.java
@romartin @hasys could you please review?
Fix issue on Lienzo that prevents the default behaviour of the native event. That was making some weird behaviour synchronizing the forms & the model.
This is part of an ensemble merge with:
https://github.com/kiegroup/lienzo-core/pull/7
https://github.com/kiegroup/kie-wb-common/pull/1419
=> JBPM-6798: Stunner & Forms - Field updates are not fired when selecting a canvas shape

src/main/java/com/ait/lienzo/client/widget/LienzoPanel.java
Hi @romartin, @pefernan, @manstis 
here is a fix for blue border around canvas. Let me know if you know better way to do so.
I will try to find a way how to disable for Widgets as well.
=> Disable blue border around canvas in Google Chrome

src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java
Hi @romartin @manstis 
Now it is possible to start selection by Middle and Right mouse buttons, but not possible to select elements. I guess we should disable middle and right buttons for selection at all.
=> Disable select action for Middle and Right mouse buttons

src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/shape/Node.java
When implementing the canvas to SVG export, it was noticed on the `Context2D` that we should be able to identify whether a container was supposed to be created /saved and when the container was closed/restored from other save/restore operations.
Distinguishing the save/restore of container nodes from other save/restore operations regarding fill, stroke, path, etc, is important when exporting the canvas to SVG and brings a more semantic and flexibility approach.
The default implementation on the `NativeContext2D` keeps the native canvas context behavior calling save/restore only, no effects when working with native canvas.
@romartin 
@mdproctor
=> JBPM-6110 Splitting Context2D save/restore to support container

src/main/java/com/ait/lienzo/Lienzo.gwt.xml, src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/INativeContext2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/Path2D.java, src/main/java/com/ait/lienzo/client/core/shape/Layer.java, src/main/java/com/ait/lienzo/client/core/shape/Node.java
Refactor creating the interface `INativeContext2D` that represents the `NativeContext2D` that is the default implementation of the native canvas context.
@romartin 
@mdproctor
=> JBPM-6110 Refactor to support injecting a INativeContext2D for SVG export

src/main/java/com/ait/lienzo/client/core/shape/AbstractMultiPathPartShape.java
Hey @hasys @tiagodolphine 
See [JBPM-7111](https://issues.jboss.org/browse/JBPM-7111)
I guess this fix must be cherry-picked to `7.7.x` as well, will let you know. 
Please can you take a quick look?
Thanks
=> JBPM-7111: Do not throw exception on size constraints validation.

src/main/java/com/ait/lienzo/client/core/shape/AbstractOffsetMultiPointShape.java, src/main/java/com/ait/lienzo/client/core/shape/PolyLine.java
See https://issues.jboss.org/browse/JBPM-6898
Before:
After:
---
- https://github.com/kiegroup/lienzo-core/pull/16
- https://github.com/kiegroup/lienzo-tests/pull/12
=> JBPM-6898: Stunner - Process is deleted when resizing task

src/main/java/com/ait/lienzo/client/core/Attribute.java, src/main/java/com/ait/lienzo/client/core/i18n/MessageConstants.java, src/main/java/com/ait/lienzo/client/core/shape/AbstractMultiPathPartShape.java, src/main/java/com/ait/lienzo/client/core/shape/Attributes.java
https://issues.jboss.org/browse/JBPM-7129
AbstractMultiPathPartShapes now supports adding min or max Constraints.
You can set minWidth, maxWidth, minHeight, maxHeight independent from
each other. For example you can set the minWidth for a shape and leave
all other constraints blank. Blank constraints will be ignored.
All this PR's are related to this task:
lienzo-core:
This PR
lienzo-tests:
https://github.com/kiegroup/lienzo-tests/pull/14
kie-wb-common
https://github.com/kiegroup/kie-wb-common/pull/1641
=> JBPM-7129 - Stunner - Allow optional size constraints for shapes 

src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeShapeHandler.java
See https://issues.jboss.org/browse/JBPM-7118
Before:
After:
---
- https://github.com/kiegroup/lienzo-core/pull/19
- https://github.com/kiegroup/lienzo-tests/pull/15
- https://github.com/kiegroup/kie-wb-common/pull/1675
=> JBPM-7118: Stunner - Mediators (zoom,pan) not working properly

src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/INativeContext2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/shape/Node.java
To allow SVG to be saved on backend with the right node id, it was necessary to insert the id o nodes on the Context2D calls, that is used by the Canvas2Svg were are using to generate the SVG based on the same calls made to draw the canvas.
@romartin 
@LuboTerifaj
=> JBPM-7145 SVG persisted on backend when saving a diagram

src/main/java/com/ait/lienzo/client/core/image/ImageProxy.java
Hey @hasys 
This is the fix for https://issues.jboss.org/browse/JBPM-7244
Includes https://github.com/kiegroup/lienzo-tests/pull/22
Thanks!
=> JBPM-7244: Fix image proxy destroy method calls (IE11)

src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/INativeContext2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/shape/Shape.java
Changes to support Diagram SVG is not highlighted on the WB (jbpm-process-svg widget).
Insert the shape id in the same way it was done for the containers.
PS: unit tests will be updated later, the PR is to be tested ASAP since this is a blocker.
@romartin 
@LuboTerifaj
=> JBPM-7245  Diagram SVG is not highlighted on the WB

src/main/java/com/ait/lienzo/client/core/shape/BezierCurve.java, src/main/java/com/ait/lienzo/client/core/types/BoundingBox.java, src/main/java/com/ait/lienzo/client/core/types/BoundingPoints.java, src/main/java/com/ait/lienzo/client/core/types/PathPartList.java, src/main/java/com/ait/lienzo/client/core/util/Geometry.java
This is the job done as in `master` branch, see https://github.com/kiegroup/lienzo-core/pull/35, but integrated into `7.7.x`.
It contains:
* Intersect using float comparison with epsilon.
* Fix on BoundingPoints when dealing with negative dimensions BoundingBox
* More efficient bezier bounding box impl
* Using NRRF_PRECISION in to prevent float point comparison errors.
I've tested and it works fine, and it helps on improving the performance in FF and IE for sure.
=> RHPAM-1015: Improve computation performance.

src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/ShapeControlUtils.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java, src/main/java/com/ait/lienzo/client/core/util/Geometry.java
Now the connector control points as a child of a shape has its position updated when the parent changes position.
Related PRs:
https://github.com/kiegroup/lienzo-tests/pull/28
https://github.com/kiegroup/kie-wb-common/pull/1863
@romartin 
@LuboTerifaj 
@hasys
=> JBPM-6882 Stunner - Control points are always pinned to a Process

src/main/java/com/ait/lienzo/client/core/Context2D.java, src/main/java/com/ait/lienzo/client/core/NativeContext2D.java, src/main/java/com/ait/lienzo/client/core/config/LienzoCore.java
Cherry pick 914635dc05196cbcf928e4b9b29ae2717b9cd8cb related to https://issues.jboss.org/browse/JBPM-7305
@romartin 
@LuboTerifaj
=> [7.7.x] RHPAM-1216 Stunner - Disable/Enable HiDPI on Stunner / Lienzo

src/main/java/com/ait/lienzo/client/core/config/LienzoCore.java
See https://issues.jboss.org/browse/RHPAM-1343
(cherry picked from commit 3808bdc4cb84a5d56a2320f3fdaa9ef686dcf05f)
=> [7.7.x] RHPAM-1343: Stunner - Setter was not setting the field

src/main/java/com/ait/lienzo/client/core/shape/wires/WiresConnector.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorControlImpl.java
Now it is now possible to move bend points of a connector outside of the canvas area.
It was necessary to set the drag bounds of the connector point handles.
@LuboTerifaj
@wmedvede (adding you to help on the review since @romartin is on PTO)
related: 
https://github.com/kiegroup/kie-wb-common/pull/2012
https://github.com/kiegroup/lienzo-tests/pull/39
=> JBPM-6883 Stunner - can't move with bend points - setting drag bounds

src/main/java/com/ait/lienzo/client/core/shape/wires/AlignAndDistribute.java, src/main/java/com/ait/lienzo/client/core/shape/wires/WiresManager.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AlignAndDistributeControlImpl.java
https://issues.jboss.org/browse/JBPM-7715
Diagram's child element attribute changes weren't been listened to.
This fixes it.
=> JBPM-7715 (Stunner) - Align and distributions are shown incorrectly for the first alignment

src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorHandlerImpl.java
Check whether the connector line has control points enabled on WiresConnectorHandlerImpl to show the transient control handle - necessary for DMN.
related https://github.com/kiegroup/lienzo-tests/pull/48
@manstis
=> DMN - Check whether the connector line has control points enabled

src/main/java/com/ait/lienzo/client/core/shape/OrthogonalPolyLine.java, src/main/java/com/ait/lienzo/client/core/shape/PolyLine.java
Hi @wmedvede, @romartin 
this is tests for fixed method which always returned true, as described here: https://github.com/wmedvede/lienzo-core/pull/1
I found out that `PolyLine#parse` method never returns `false` value.
Array newer will be null, but can be empty. Also some usages `WiresConnector#updateHeadTailForRefreshedConnector` of this method relay that if this method returns `true` it means there are some values and starts to use it's values:
**`WiresConnector#updateHeadTailForRefreshedConnector`**
```java
final boolean prepared = line.isPathPartListPrepared(c.getLine().getAttributes());
if (!prepared)
{
return true;
}
Point2DArray points     = line.getPoint2DArray();
Point2D      p0         = points.get(0);
```
**`AbstractOffsetMultiPointShape#isPathPartListPrepared`**
```java …
```
=> Fix possible OutOfRange exception

src/main/java/com/ait/lienzo/client/widget/LienzoPanel.java
Hey @hasys @manstis 
Can you please check this quick fix for [RHPAM-1681](https://issues.jboss.org/browse/RHPAM-1681)
TBH I don't know how to correctly test this, even running a `GWTTestCase` (which runs a jetty etc)... it's an IE11 specific thing, so at much we can consider some integration test (selenium?), rather than a unit test... anyway if you have some other idea for fixing or testing this will be appreciated! :+1: 
PS: Tested on Chrome, FF, IE11 and Edge.
Relates to https://github.com/kiegroup/kie-wb-common/pull/2280
Thanks guys!!
=> RHPAM-1681: Focusing the lienzp panel in IE11 scrolls the parent one, if any, to left-top corner.

src/main/java/com/ait/lienzo/client/widget/LienzoPanel.java
Hey @hasys 
This is the cherry-pick for the IE11 fix for `master` branch. 
Thanks!
=> RHPAM-1681: Focusing the lienzp panel in IE11 scrolls the parent one if any, to left-top corner

src/main/java/com/ait/lienzo/client/core/shape/wires/AlignAndDistribute.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/AlignAndDistributeControl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AlignAndDistributeControlImpl.java, src/main/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImpl.java
https://issues.jboss.org/browse/JBPM-8014
The problem was AlignAndDistributeControlImpl.updateIndex() was called
mid drag. To fix this the same behavior that happened is now called
when the drag is cancelled.
=> JBPM-8014 (Stunner) - Drag cancel causes an error

src/main/java/com/ait/lienzo/client/core/shape/AbstractMultiPathPartShape.java
See https://issues.jboss.org/browse/DROOLS-3406
This exposes some bits to allow re-use by a new control point to handle moving a "splitter".
- https://github.com/kiegroup/lienzo-core/pull/81
- https://github.com/kiegroup/kie-wb-common/pull/2372
=> DROOLS-3406: [DMN Designer] Decision Service splitter should be movable

src/main/java/com/ait/lienzo/client/core/shape/wires/SelectionManager.java
Hi @romartin, @treblereel,
I found small regression after https://github.com/kiegroup/lienzo-core/pull/86
When you do group selection - selection is created, but nodes are not decorated. You should click on selection one more time to change decoration to selected mode.
I already have a fix for it, but Jira is down, so I can't report an issue for it. So sending PR without issue. Tomorrow I have a PTO, so see you Monday.
CC @LuboTerifaj 
Tests for this PR https://github.com/kiegroup/lienzo-tests/pull/70
=> JBPM-8341: Selected decoration doesn't applied to nodes for group selection

src/main/java/com/ait/lienzo/client/widget/panel/mediators/PanelMediators.java
On this PR:
- Added parameters to PanelMediator to change the Zoom and Pan keys. Cmd should be used instead of Ctrl on macOS.
Related PRs:
https://github.com/kiegroup/lienzo-core/pull/102
https://github.com/kiegroup/lienzo-tests/pull/84
https://github.com/kiegroup/appformer/pull/922
https://github.com/kiegroup/kie-wb-common/pull/3221
https://github.com/kiegroup/kogito-tooling/pull/86
=> KOGITO-766: Kogito Keyboard Shortcuts API
